### ISSUE TITLE
Lock screen orientation

### ISSUE THREAD

**Issue by rom1v** [psa-jforestier/makesomenoise#2]
The gesture to "make some noise" often unintentionally causes the screen to rotate (portrait → landscape → portrait).

Maybe the screen could be forced in portrait mode (hardcoded) or a button could be added to lock/unlock the orientation.

Cheers

**Comment by psa-jforestier** [comment]
Will be fixed in 1.2.5 : 
- lock orientation when whip gesture is detected
- unlock orientation when sound is stopped

**Comment by psa-jforestier** [comment]
Fixed in https://github.com/psa-jforestier/makesomenoise/releases/tag/1.2.5
