### ISSUE TITLE
typo on suspense button

### ISSUE THREAD

**Issue by grrrrr** [psa-jforestier/makesomenoise#3]
For the `suspense` button it is incorrectly listed as `suspens` without the `e` at the end.

This also occurs in the README.md

**Comment by grrrrr** [comment]
opened /pull/4. If accepted, relevant screenshots would need to be updated

**Comment by psa-jforestier** [comment]
thank you for typo fixing!

**Comment by psa-jforestier** [comment]
Fixed in https://github.com/psa-jforestier/makesomenoise/releases/tag/1.2.5
